# Create api version v1 for postgres database with label: tier => db-tier
# container name: postgres 
# container image: postgres
# container environtment: POSTGRES_PASSWORD => mysecretpassword
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    tier: db-tier
spec:
  containers:
    - name: postgres
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: mysecretpassword